---
# tasks file for namenoderole
- name: Copying hadoop and jdk softwares
  copy:
          src: "files/{{ item }}"
          dest: "/root/"
  loop:
          - jdk-8u171-linux-x64.rpm
          - hadoop-1.2.1-1.x86_64.rpm

- name:  Checking whether  Hadoop is installed or not
  command: "rpm  -q  hadoop"
  ignore_errors: yes
  register: x

- name:  Checking whether  Java is installed or not
  command: "java -version"
  ignore_errors: yes
  register: y

- debug:
      var: y


- name:  Installing JDK 
  command:  "rpm  -ivh  jdk-8u171-linux-x64.rpm"
  when:   y.rc != 0  
  ignore_errors: yes

- name:  Installing  hadoop
  command:  "rpm  -ivh  hadoop-1.2.1-1.x86_64.rpm  --force"
  when:  x.rc != 0
  ignore_errors:  yes


- name:  Creating directory for NN
  file:
          state:  directory
          path:  "{{ dir_name }}"

- name:  Copying hdfs-site and core-site
  template:
          src:  "templates/{{ item }}"
          dest:  "/etc/hadoop/{{ item }}"
  loop:
          - hdfs-site.xml
          - core-site.xml

- name:  Formatting Namenode
  shell:  "echo Y | hadoop  namenode  -format"
  register: format
  ignore_errors:  yes

- name: Printing format status
  debug:
          var: format.stderr_lines 

- name: success code
  shell: "jps"
  register: success

- name:  Printing Service status
  debug:
          var:  success  

- name:  starting namenode service
  command:  "hadoop-daemon.sh  start namenode"
  ignore_errors:  yes

- name:  starting namenode service
  command:  "hadoop-daemon.sh  restart namenode"
  ignore_errors:  yes


- name:  Printing Service success code
  debug:
     var: success.stdout_lines

           
